#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

pgrep -x dex > /dev/null || dex -a&
feh --bg-fill ~/.config/.wallpaper.png
pgrep -x powerkit > /dev/null || powerkit&
pgrep -x picom > /dev/null || picom -b
pgrep -x dunst > /dev/null || dunst&
pgrep -x mpd > /dev/null || mpd&
pgrep -x xautolock > /dev/null || xautolock -time 5 -locker /usr/bin/i3lock-fancy -detectsleep&

bspc monitor -d 1 2 3 4 5 6
bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

xinput set-prop 'ETPS/2 Elantech Touchpad' 'libinput Tapping Enabled' 1

~/.config/polybar/launch.sh  &
~/.config/bspwm/bin/cleanfullscreen &

bspc config border_width        2
bspc config window_gap          10

bspc config borderless_monocle   true
bspc config focus_follows_pointer true
bspc config split_ratio 0.5

#bspwm color config
bspc config normal_border_color "#1f2335"
bspc config active_border_color "#2ac3de"
bspc config focused_border_color "#7dcfff"
bspc config presel_feedback_color "#565f89"
