#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4

case "$class" in
	kitty|alacritty|*terminal)
		echo "state=tiled desktop=1 follow=on" ;;
	Brave*|Firefox|firefox|qutebrowser)
		echo "state=tiled desktop=2 follow=on" ;;
	Pcsx2)
		echo "state=floating desktop=3 center=on"	;;
	Telegram*)
		echo "state=tiled desktop=5" ;;
	zoom*|Zoom*|*join*)
		echo "state=floating desktop=6 follow=on center=on"	;;
	mpv)
		echo "state=fullscreen" ;;
	Steam|steam|Pcmanfm)
		echo "state=floating desktop=6 center=on"
esac
