#!/usr/bin/python

from pyrof.rofi import Rofi
import os

menu = {
    "360p": "360",
    "480p": "480",
    "720p": "720",
}

rofi = Rofi()
rofi.base_command = ['rofi', '-no-default-config']
rofi.font = 'FiraCode Nerd Font 14'
rofi.dmenu = True
rofi.theme_str = "listview { lines: 3; } window { width: 250px; }"
rofi.theme_str += "inputbar { children: [prompt]; }"
rofi.prompt = 'Play with MPV'
rofi = rofi(menu)

fmt = "fsd/std/bestvideo[ext=mp4][height<=?"+rofi.value+"]+"
fmt += "bestaudio/[height<=?"+rofi.value+"]/bestvideo[ext=mp4]+bestaudio/best"

os.system("mpv --no-config --ytdl-format=" + fmt + " " + os.getenv('QUTEURL'))
