#!/usr/bin/sh

MENU="360|480|720"
THEMESTR="listview{lines:3;}"
THEMESTR+="window{width:250px;}"
THEMESTR+="inputbar{children:[prompt]}"
PROMPT="Youtube Download"

ROFI=$(rofi -dmenu -no-default-config -p "$PROMPT" -sep "|" -theme-str "$THEMESTR" <<< $MENU)

FMT="fsd/std/bestvideo[ext=mp4][height<=?$ROFI]+"
FMT+="bestaudio/[height<=?$ROFI]/bestvideo[ext=mp4]+bestaudio/best"

mpv --no-config --ytdl-format=$FMT $QUTEURL
