#!/usr/bin/sh

MENU="360|480|720"
THEMESTR="listview{lines:3;}"
THEMESTR+="window{width:250px;}"
THEMESTR+="inputbar{children:[prompt];}"
PROMPT="Youtube Download"
VIDPATH='/mnt/Data/Video/Download/%(title)s.%(ext)s'

ROFI=$(rofi -dmenu -no-default-config -p "$PROMPT" -sep "|" -theme-str "$THEMESTR" <<< $MENU)

FMT="fsd/std/bestvideo[ext=mp4][height<=?$ROFI]+"
FMT+="bestaudio/[height<=?$ROFI]/bestvideo[ext=mp4]+bestaudio/best"

kitty -e yt-dlp $QUTE_URL -f $FMT -o $VIDPATH
